'use client'

import Image from 'next/image'
import { ArrowLeft, Check, Mail, Send } from 'lucide-react'
import { features, news, seoContent } from '@/lib/site-data'

export function StatusBanner() { return <section className="border-y border-white/10 bg-[#0d0b14] py-5"><div className="container-shell flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">در حال آماده‌سازی مرجع فارسی دنیای GTA</p><p className="mt-1 text-xs text-muted">نسخه اولیه سایت در حال توسعه است</p></div><div className="w-full max-w-sm"><div className="mb-2 flex justify-between text-xs text-muted"><span>پیشرفت پروژه</span><span className="text-primary">۷۸٪</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[78%] animate-line rounded-full bg-gradient-to-l from-primary to-secondary"/></div></div></div></section> }
export function Features() { return <section id="features" className="section-pad"><div className="container-shell"><div className="mb-12 max-w-2xl"><p className="mb-4 text-sm font-bold text-primary">آنچه در راه است</p><h2 className="text-balance text-3xl font-black tracking-tight sm:text-5xl">همه چیز درباره دنیای GTA</h2><p className="mt-5 text-lg leading-8 text-muted">GTA World قرار است مرجع کاملی برای دنیای Grand Theft Auto باشد.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, description, label }) => <article key={title} className="group rounded-3xl border border-white/10 bg-card/70 p-6 transition duration-300 hover:-translate-y-1 hover:border-primary/35 hover:bg-[#171322]"><div className="mb-10 flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl border border-primary/20 bg-primary/10 text-primary transition group-hover:scale-110 group-hover:bg-primary group-hover:text-white"><Icon size={22}/></span><span className="rounded-full bg-secondary/10 px-3 py-1 text-[11px] text-secondary">{label}</span></div><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted">{description}</p></article>)}</div></div></section> }
export function NewsPreview() { return <section id="news" className="section-pad border-t border-white/5 bg-[#0c0a12]"><div className="container-shell"><div className="mb-12 flex items-end justify-between gap-6"><div><p className="mb-4 text-sm font-bold text-primary">از دنیای GTA</p><h2 className="text-3xl font-black sm:text-5xl">آخرین اخبار دنیای GTA</h2></div><a href="#newsletter" className="hidden items-center gap-2 text-sm font-bold text-muted transition hover:text-primary sm:flex">مشاهده همه <ArrowLeft size={16}/></a></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{news.map(item => <article key={item.title} className="group overflow-hidden rounded-3xl border border-white/10 bg-card transition hover:-translate-y-1 hover:border-primary/30"><div className="relative aspect-[16/10] overflow-hidden"><Image src={item.image} alt={item.title} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#12101b] to-transparent opacity-70"/>{item.unconfirmed && <span className="absolute right-4 top-4 rounded-full bg-accent px-3 py-1 text-[10px] font-bold text-white">شایعه / تأییدنشده</span>}</div><div className="p-5"><div className="flex items-center gap-3 text-xs text-muted"><span className="text-primary">{item.category}</span><span className="h-1 w-1 rounded-full bg-border"/><span>{item.date}</span></div><h3 className="mt-4 text-lg font-bold leading-8 transition group-hover:text-primary">{item.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-7 text-muted">{item.summary}</p><a href="#about" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-foreground hover:text-primary">بیشتر بخوانید <ArrowLeft size={15}/></a></div></article>)}</div></div></section> }
export function SeoIntroduction() { return <section id="about" className="section-pad"><div className="container-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="mb-4 text-sm font-bold text-primary">راهنمای شروع</p><h2 className="text-3xl font-black leading-tight sm:text-5xl">GTA World؛ دنیای GTA به زبان فارسی</h2></div><div className="rounded-3xl border border-white/10 bg-card/60 p-6 sm:p-10"><div className="whitespace-pre-line text-base leading-9 text-muted">{seoContent}</div></div></div></section> }
export function Newsletter() { return <section id="newsletter" className="section-pad"><div className="container-shell"><div className="relative overflow-hidden rounded-[2rem] border border-primary/25 bg-[linear-gradient(120deg,#171021,#100d19)] p-7 sm:p-12"><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-primary/10 blur-3xl"/><div className="relative grid items-center gap-10 lg:grid-cols-[1fr_.9fr]"><div><div className="mb-5 inline-flex rounded-full border border-primary/30 bg-primary/10 p-3 text-primary"><Mail size={20}/></div><h2 className="text-3xl font-black sm:text-5xl">از دنیای GTA باخبر بمان</h2><p className="mt-5 max-w-lg leading-8 text-muted">مهم‌ترین اخبار GTA VI، آپدیت‌ها و اتفاقات دنیای Grand Theft Auto را از دست نده.</p></div><NewsletterForm/></div></div></div></section> }
function NewsletterForm() { return <form className="relative" onSubmit={(e) => { e.preventDefault(); const form = e.currentTarget; const input = form.elements.namedItem('email') as HTMLInputElement; const out = form.querySelector('[data-status]') as HTMLElement; if (!input.validity.valid) { input.focus(); out.textContent = 'لطفاً یک ایمیل معتبر وارد کن.'; out.className = 'mt-3 text-sm text-accent'; return } out.textContent = 'با تشکر! ایمیل شما ثبت شد.'; out.className = 'mt-3 text-sm text-primary'; form.reset() }}><label htmlFor="email" className="sr-only">ایمیل شما</label><div className="flex flex-col gap-3 sm:flex-row"><input id="email" name="email" type="email" required placeholder="ایمیل شما" className="min-h-14 flex-1 rounded-2xl border border-white/15 bg-black/20 px-5 text-sm text-foreground outline-none transition focus:border-primary"/><button type="submit" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-primary px-6 font-bold text-white transition hover:bg-[#f35eaa]">خبرم کن <Send size={16}/></button></div><p data-status className="mt-3 text-sm text-muted">بدون اسپم؛ فقط اخبار مهم دنیای GTA.</p></form> }
export function EasterEgg() { return <button type="button" aria-label="Easter egg" onClick={() => alert('کد مخفی فعال شد؛ به Vice City خوش آمدی.')} className="fixed bottom-5 left-5 z-10 hidden rounded-full border border-white/10 bg-[#12101b]/70 px-3 py-2 font-mono text-[10px] text-muted transition hover:border-primary/50 hover:text-primary sm:block">↑ ↑ ↓ ↓ ← →</button> }
